### PR TITLE
Adding an option to remove the css output.

### LINKED ISSUE #56: Add Filter to disable CSS
On a client's site of mine, when editing the colors for the plugin, the default CSS is overriding the custom CSS in the `head`.

CSS Outputted:

```css
/* Custom CSS */
.simple-social-icons ul li a,
.simple-social-icons ul li a:hover,
.simple-social-icons ul li a:focus {
    background-color: #ffffff !important;
    border-radius: 60px;
    color: #000000 !important;
    border: 0px #ffffff solid !important;
    font-size: 30px;
    padding: 15px;
}
/* Theme Defaults CSS */
.simple-social-icons ul li a:hover,
.simple-social-icons ul li a:focus {
    background-color: #f04848 !important;
    border-color: #ffffff !important;
    color: #ffffff !important;
}
.simple-social-icons ul li a:focus {
    outline: 1px dotted #f04848 !important;
}
```

I'm not sure if this is a theme issue (Brunch is over-specific), or a plugin issue — I'm guess the former but wanted to make sure. We are also hosting the site on Synthesis if more information is needed.

### PR DESCRIPTION
**Pull request by marksabbath**
Should fix #56

### CODE REVIEW

**Comment by marksabbath** [comment]
Hey, @nickcernis If I'm not mistaken, this pull request should resolve #56 

Would you mind reviewing it?

Thanks in advance :)

**Comment by marksabbath** [comment]
It totally makes sense to me @nickcernis 

I've made those changes since the user in the thread was complaining directly about that code, and thought it could be useful.

I'm more than happy to create a filter to remove all the CSS if it would be better, just let me know and I'll be promptly working on this :)

**Comment by susannelson** [comment]
@nickcernis I agree it would be better to make a filter instead of an option in the widget.

My only thought is that users might be confused about why there are no settings available in the widget when they see them mentioned in KB articles.

As you said, it would be up to the theme developers to make it clear about why the regular settings aren't available. :)

**Comment by nickcernis** [comment]
@marksabbath @susannelson Thanks for the feedback on this. It looks like the path forward is:

- Add a filter named “simple_social_disable_custom_css” or similar (value is false by default).
- If true:
    - Disable output of custom CSS in the `css()` function. (`enqueue_css()` already has its own filter.)
    - Disable output of all styling fields in `form()`.
- Mention in the filter docs that theme developers should warn their users about missing options. (“If setting this filter to true, we recommend mentioning in your theme documentation that Simple Social Icons widget settings will have display styling options, as your theme styles icons for them.”)

**Comment by marksabbath** [comment]
Closing, should be addressed by #80

**Pull request closed without merging**
