### PR TITLE
Add TikTok social option

### PR DESCRIPTION
**Pull request by s-kumar72**
Add the option for a TikTok social icon.

### How to test

1. Open the Simple Social Icons plugin on this branch & open widget in dashboard
2. Add a link to the 'TikTok URI' form field
3. On the actual site, a TikTok icon should be present & when clicked, it should link to the correct place

### Suggested changelog entry

- Add TikTok social icon to default settings

### CODE REVIEW

**Review by kienstra — APPROVED** [review]
Hi @s-kumar72,
Really nice work!

`tiktok.svg` is 4K, like other .svg` files here.

And it looks good in the front-end and editor:

Screen Shot 2022-07-15 at 4 41 57 PM

**Comment by kienstra** [comment]
Let's wait until Monday to see if anyone else wants to review this, then feel free to merge it.

**Review by Mewjaden — APPROVED** [review]
[] www.tiktok.com/@_zahher

**Comment by kienstra** [comment]
Please ignore the [review above](https://github.com/studiopress/simple-social-icons/pull/119#pullrequestreview-1040986641).

**Review by dreamwhisper — APPROVED** [review]
@s-kumar72 This looks really good! Nice job!

**Comment by kienstra** [comment]
@s-kumar72,
Great job with this. Feel free to merge this.

Let's plan a release to get this out. Maybe in this sprint.

**Review by mike-day — APPROVED** [review]
Nice work, @s-kumar72!

**Pull request merged**
